### ISSUE TITLE
Настроить auto merge для PR

### ISSUE THREAD

**Issue by eugene-krivobokov** [avito-tech/avito-android#17]
Когда прошли все проверки PR,
хочу чтобы он смержился автоматически.

Варианты реализации:
- https://github.com/palantir/bulldozer

**Comment by eugene-krivobokov** [comment]
Предлагаю пока договориться о джентельменском соглашении, 
делать вручную если в заголовке PR есть теги:
- `[MERGE_WHEN_READY] `
- `[WIP]`, `[DO_NOT_MERGE]`

@dsvoronin , ?

**Comment by dsvoronin** [comment]
мне ок!
