### ISSUE TITLE
Should we abandon testFixtures usage?

### ISSUE THREAD

**Issue by dsvoronin** [avito-tech/avito-android#295]
There is a problem that really hurts our productivity:

https://github.com/avito-tech/avito-android/blob/1016aeca15b71f7c7190b3d959bcbae6731c4ec9/gradle.properties#L7-L11

Should we drop it for more straightforward approach, at least temporary?

First thing comes to mind is just place fixtures in runtimeClasspath and package it this regular code?
It looks dirty, but we can use some additional instruments to point out it's "testing only" purpose.
Like maybe https://kotlinlang.org/docs/reference/opt-in-requirements.html custom annotation, or maybe you know better ways.

**Comment by eugene-krivobokov** [comment]
What about an old and straightforward solution with standalone modules?

**Comment by dsvoronin** [comment]
> What about an old and straightforward solution with standalone modules?

well, its better in any way than my variant

only thing i struggle with is understanding the dependencies in separate test modules, but i'm in

**Comment by emartynov** [comment]
Test fixtures are coming to AGP 7.0
