### ISSUE TITLE
Переименовать kotlin-dsl-support

### ISSUE THREAD

**Issue by dsvoronin** [avito-tech/avito-android#60]
### Проблема

название не отражает содержимого, на самом деле там и `kotlin-dsl-support` и наши экстеншены для gradle, в том числе и те что для вызова из groovy

Скорее что-то вроде: `gradle-api-extensions`

**Comment by eugene-krivobokov** [comment]
Обсудили, что теперь можем использовать публичный kotlin-dsl из gradle, избавиться от многих  наших велосипедов.
