### ISSUE TITLE
'checkBuildEnvironment' not found on a KMM project with Cocoapods

### ISSUE THREAD

**Issue by PhilipDukhov** [avito-tech/avito-android#607]
I'm using build checks on a kotlin multiplatform project. At first I was using a regular setup (project generated with the [android studio plugin](https://plugins.jetbrains.com/plugin/14936-kotlin-multiplatform-mobile)), and it worked well. But then I moved my shared project to cocoapods using [this guide](https://kotlinlang.org/docs/reference/native/cocoapods.html), build checks started failing with the following error:
```
* What went wrong:
Task 'checkBuildEnvironment' not found in project ':shared'.
```
I'd created a [sample project](https://github.com/PhilipDukhov/AvitoBuildchecksCocoapods) which shows the error
In case you don't have Xcode, you can just test it with 
```
 ./gradlew -p shared :shared:syncFramework -Pkotlin.native.cocoapods.target=ios_x64 -Pkotlin.native.cocoapods.configuration=Debug -Pkotlin.native.cocoapods.cflags= -Pkotlin.native.cocoapods.paths.headers= '-Pkotlin.native.cocoapods.paths.frameworks= "shared/build/cocoapods/framework"'
```
that's the command run by xcode in order to build the module.

**Comment by eugene-krivobokov** [comment]
Thanks for the sample! We'll look into it.

Before a fix, you can disable the plugin by `avito.build-checks.enabled` property in gradle.properties.

**Comment by eugene-krivobokov** [comment]
Can you please explain the reasons to use a custom project dir in a sample?
```
./gradlew -p shared :shared:syncFramework
```
The `shared` module is a regular module, not an included build. I don't see a difference with a variant with a default project dir:
```
./gradlew :shared:syncFramework
```

**Comment by PhilipDukhov** [comment]
it's generated by [cocoapods](https://kotlinlang.org/docs/reference/native/cocoapods.html) plugin, I don't know the reasons🤪
