### ISSUE TITLE
Tool proposal for docs translation

### ISSUE THREAD

**Issue by ilyaspiridonov** [avito-tech/avito-android#741]
Hi team, it looks like documentation for this project is written in Russian originally and then translated into English (saw some of the docs are partially translated). 
Wondering if you would be open to checking out a free localization tool that we are developing: gitlocalize.com 
It syncs with GitHub, supports .md and can hopefully make your translation efforts easier. 
Feel free to shoot me an email at ilya[at]gitlocalize.com if you have any questions or need help with setting up a project.
Cheers, 
-I

**Comment by sergioboi** [comment]
Thank you for the proposal. We will discuss it and contact you later
