### ISSUE TITLE
Downloading gradlew each docker run of android-builder

### ISSUE THREAD

**Issue by materkey** [avito-tech/avito-android#778]
Wrote a similar Dockerfile and now I see downloading of gradlew despite I have volumes for gradle and gradlew caches
![image](https://user-images.githubusercontent.com/17577010/107821491-9dc9da80-6d8d-11eb-9301-da7c3cf237ed.png)

Glad if you can check if this issue is reproducible in your infrastructure
![image](https://user-images.githubusercontent.com/17577010/107823690-39a91580-6d91-11eb-8379-dda0d111f716.png)

**Comment by dsvoronin** [comment]
Thanks for the report!

Take a look at #782
Caches should not work aswell without adding GRADLE_USER_HOME env
Seems like i missed it in open-source project build

Please add this variable and let me know if it helps; it definetily helped our opensource build to run faster now

**Comment by materkey** [comment]
It works! Thank you!
